# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitcentral', '0003_auto_20160226_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gitcentral.Repo'),
        ),
        migrations.AlterField(
            model_name='repopermission',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='repopermission',
            name='permission',
            field=models.IntegerField(choices=[(0, 'Read-only'), (1, 'Read-Write'), (2, 'Admin')], default=0),
        ),
    ]
